f_django/f_django/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='acceuil'),
    path('projet_nan/', include('projet_nan.urls')),
]

f_django/projet_nan/urls.py
from django.urls import path

from . import views

app_name = 'projet_nan'
urlpatterns = [

    path('', views.home),
    path('match', views.match),
    path('articles', views.articles),
    path('resultat', views.date_actuelle, name='football'),
    path('addition/<int:nombre1>/<int:nombre2>/', views.addition),
    # path('scrap', views.scrap),


]

f_django/projet_nan/models.py
from django.db import models

# Create your models here.

f_django/f_django/views.py
from django.shortcuts import render

def home(request):
	return render(request, 'index.html')

f_django/projet_nan/views.py
from django.shortcuts import render
from django.http import HttpResponse
from datetime import datetime
from django.http import JsonResponse
import json

from requests import get
from bs4 import BeautifulSoup

def match(request):
    return render(request, 'projet_nan/match.html')

def home(request):

    """ Exemple de page non valide au niveau HTML pour que l'exemple soit concis """

    return HttpResponse("""

        <h1>Bienvenue sur mon blog !</h1>

        <p>Les crêpes bretonnes ça tue des mouettes en plein vol !</p>

    """)

def articles(request):

    """ Exemple de page non valide au niveau HTML pour que l'exemple soit concis """

    return HttpResponse("""

        <h1>Première article </h1>

        <p>Soyez attentifs !!!</p>

    """)

 #def date_actuelle(request):
     #return render(request, 'projet_nan/date.html', {'date': datetime.now()})


def addition(request, nombre1, nombre2):    
    total = nombre1 + nombre2

    # Retourne nombre1, nombre2 et la somme des deux au tpl
    return render(request, 'projet_nan/addition.html', locals())

def date_actuelle(request):

    url = 'https://www.matchendirect.fr/'
    response = get(url)
    html_soup = BeautifulSoup(response.text, 'html.parser')

    table = html_soup.find('div', attrs = {'id':'livescore'}) 
    compt = 1

    mydata = []


    for row in table.findAll('div', attrs = {'class':'panel panel-info'}): 


        a_desc = row.find('h3', attrs = {'class':'panel-title'}).get_text() 

        for el in row.findAll('tr'):

            resultat = {}
            heure = el.find('td', attrs = {'class':'lm1'}).get_text() 
            eqA = el.find('span', attrs = {'class':'lm3_eq1'}).get_text()
            eqB =  el.find('span', attrs = {'class':'lm3_eq2'}).get_text()

            scors =  el.find('span', attrs = {'class':'lm3_score'}).get_text()

            resultat['heure'] = heure
            resultat['eqa'] = eqA
            resultat['eqb'] = eqB
            resultat['scors'] = scors

            mydata.append(resultat)

    data = mydata
    
    return render(request, 'projet_nan/resultat.html', {'result': data}) # retourn du json
# Create your views here.

f_django/projet_nan/templates/projet_nan/addition.html
<h1>Ma super calculatrice</h1>
<p>{{ nombre1 }} + {{ nombre2 }}, ça fait <strong>{{ total }}</strong> !<br />
Nous pouvons également calculer la somme dans le template : {{ nombre1|add:nombre2 }}.</p>

f_django/projet_nan/templates/projet_nan/match.html
{% extends 'index.html' %}

{% block title %} 
inscription 
{% endblock %}
{% block card %}
{% endblock %}

{% block adjobi %}
<nav class="mb-1 navbar navbar-expand-lg navbar-dark">
  <a class="navbar-brand" href="#">SPORTfASH</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
    aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">ACCUEUIL
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">FOOTBALL</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">BASKETBALL</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">AUTRE
        </a>
        <div class="dropdown-menu dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
          <a class="dropdown-item" href="#">TENNIS</a>
          <a class="dropdown-item" href="#">VOLEYBALL</a>
          <a class="dropdown-item" href="#">HANDBALL</a>
        </div>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto nav-flex-icons">
      <li class="nav-item">
        <a class="nav-link waves-effect waves-light">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link waves-effect waves-light">
          <i class="fab fa-google-plus-g"></i>
        </a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right dropdown-default"
          aria-labelledby="navbarDropdownMenuLink-333">
          <a class="dropdown-item" href="#">CONNEXION</a>
          <a class="dropdown-item" href="#">CONTACT</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
{% endblock %}

f_django/projet_nan/templates/projet_nan/resultat.html
{% extends 'index.html' %}
{% load static %}
{% block title %}SPORTRESULTATS{% endblock %}
{% block affiche %}
<div class="container card text-center" style="background-color: black">
  <div class="card-body" style="background-image: url('{% static 'img/heading.jpg'%}');">
    <h1 class="card-title" style="font-weight:bold; color: white">RESULTAT DES MATCHS DU JOUR</h1>
    <h2 class="card-text">suivez le resultat des match en direct.</h2>
  </div>
</div>
{% endblock %}


{% block body %}

<!-- Editable table -->
<div class="card">
  <h3 class="card-header text-center font-weight-bold text-uppercase py-4">MATCH DU JOUR</h3>
  <div class="card-body">
    <div id="table" class="table-editable">
      <span class="table-add float-right mb-3 mr-2"><a href="https://1xbet26.com/fr/live/" class="text-success"><i
            class="fas fa-plus fa-2x" aria-hidden="true"></i></a></span>
      <table class="table table-bordered table-responsive-md table-striped text-center">
        <thead>
          <tr class="p-0">
            <th class="text-center">HEURE</th>
            <th class="text-center">EQUIPE 1</th>
             <th class="text-center">SCORE</th>
            <th class="text-center">EQUIPE 2</th>
           
           
            
          </tr>
        </thead>
        <tbody>
        	{% for res in result %}
          <tr class="p-0">
          	
          	 <td>
              <span class="table-remove"><button type="button"
                  class="btn btn-default btn-rounded btn-sm my-0">{{res.heure}}</button></span>
            </td>
           
            <td class="pt-3-half" contenteditable="true">{{res.eqa}}</td>

             <td>
              <span class="table-remove"><button type="button"
                  class="btn btn-danger btn-rounded btn-sm my-0">{{res.scors}}</button></span>
            </td>

            <td class="pt-3-half" contenteditable="true">{{res.eqb}}</td>
            
            <td class="pt-3-half">
              <span class="table-up"><a href="#!" class="indigo-text"><i class="fas fa-long-arrow-alt-up"
                    aria-hidden="true"></i></a></span>
              <span class="table-down"><a href="#!" class="indigo-text"><i class="fas fa-long-arrow-alt-down"
                    aria-hidden="true"></i></a></span>
            </td>

             <td>
              <span class="table-remove"><button type="button"
                  class="btn btn-success btn-rounded btn-sm my-0">parier</button></span>
            </td>


          </tr>
   
            </td>
          </tr>
           {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
  

{% endblock %}

  {% block pub %}
          <!--Grid column-->

        <!-- Video -->
          <div class="embed-responsive embed-responsive-16by9">
          <img class="embed-responsive-item" src="https://www.liveonscore.com/wp-content/uploads/2018/06/feature.image2_.png" allowfullscreen>>
          </div>
      <div class="embed-responsive embed-responsive-16by9">
          <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/X4USsy7RWN8"
          allowfullscreen></iframe>
        </div>

         <div class="embed-responsive embed-responsive-16by9">
          <img class="embed-responsive-item" src="http://www.lesurfgagnant.com/images/stories/paris/paris-sportifs-comparatif.jpg" allowfullscreen>>
          </div>
      <div class="embed-responsive embed-responsive-16by9">
          <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/ZQP7R6pfaXg"
          allowfullscreen></iframe>
        </div>

         <div class="embed-responsive embed-responsive-16by9">
          <img class="embed-responsive-item" src=" https://images.ladepeche.fr/api/v1/images/view/5c3790ab3e454661ac177149/large/image.jpg" allowfullscreen>>
          </div>

        
      
 {% endblock %}

f_django/templates/index.html
{% extends "source.html" %}
{% load static %}
{% block title %}SPORTFLSH{% endblock %} 

 {% block body %}
 <!-- Card Dark -->
<div class="card">

  <!-- Card image -->
  <div class="view overlay">
    <img class="card-img-top" src="{% static 'img/pari.jpg'%}" alt="Card image cap">
    <a>
      <div class="mask rgba-white-slight"></div>
    </a>
  </div>

  <!-- Card content -->
  <div class="card-body elegant-color white-text rounded-bottom">

    <!-- Social shares button -->
    <a class="activator waves-effect mr-4"><i class="fas fa-share-alt white-text"></i></a>
    <!-- Title -->
    <h4 class="card-title">parier</h4>
    <hr class="hr-light">
    <!-- Text -->
    <p class="card-text white-text mb-4">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <!-- Link -->
    <a href="{% url 'projet_nan:football' %}" class="white-text d-flex justify-content-end"><h5>MATCH DU JOUR <i class="fas fa-angle-double-right"></i></h5></a>

  </div>

</div>
<!-- Card Dark -->
  {% endblock %}



  {% block pub %}
       <div class="embed-responsive embed-responsive-16by9 mb-4">
          <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/UrA0CtEQciQ"
          allowfullscreen></iframe>
        </div>  

         <div class="embed-responsive embed-responsive-16by9">
          <img class="embed-responsive-item" src="http://www.lesurfgagnant.com/images/stories/paris/paris-sportifs-comparatif.jpg" allowfullscreen>>
          </div>
           <div class="embed-responsive embed-responsive-16by9">
          <img class="embed-responsive-item" src=" https://images.ladepeche.fr/api/v1/images/view/5c3790ab3e454661ac177149/large/image.jpg" allowfullscreen>>
          </div> 
  {% endblock %}
  

f_django/templates/source.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}SPORTFLSH{% endblock %} </title>
  {% load static %}
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body style="background-color:black;">
  {% block adjobi %}
  <!-- Start your project here-->
  <!--Navbar -->
<nav class="mb-1 navbar navbar-expand-lg navbar-dark">
  <a class="navbar-brand" href="#">SPORTfASH</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
    aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'acceuil' %}">ACCUEUIL
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'projet_nan:football' %}">FOOTBALL</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">BASKETBALL</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">AUTRE
        </a>
        <div class="dropdown-menu dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
          <a class="dropdown-item" href="#">TENNIS</a>
          <a class="dropdown-item" href="#">VOLEYBALL</a>
          <a class="dropdown-item" href="#">HANDBALL</a>
        </div>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto nav-flex-icons">
     
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right dropdown-default"
          aria-labelledby="navbarDropdownMenuLink-333">
          <a class="dropdown-item" href="#">CONNEXION</a>
          <a class="dropdown-item" href="#">CONTACT</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
<!--/.Navbar -->
  <!-- /{Start} your project here-->
  {% endblock %}

  
{% block affiche %}
<div class="container card text-center" style="background-color: black">
  <div class="card-body" style="background-image: url('{% static 'img/heading.jpg'%}');">
    <h1 class="card-title" style="font-weight:bold; color: white">JUSQU'A 100% OFFERTS</h1>
    <h2 class="card-text">suivez le resultat des match en direct.</h2>
    <a href="#!" class="btn btn-primary">je m'inscrit</a>
  </div>
</div>
{% endblock %}


<div class="row">

  <div class="col-md-6 offset-1">
     {% block body %}
  {% endblock %}
  </div>

   <div class="col-md-4">
     {% block pub %}
  {% endblock %}
  </div>

</div>


 
      

    
<!-- Card -->
<!--<div class="row">
  
    {% block resultat %}{% endblock %}
 
</div>-->

<!-- Footer image-->
<footer class="page-footer font-small mdb-color lighten-3 pt-4">

  <!-- Footer Elements -->
  <div class="container">

    <!--Grid row-->
    <div class="row">

      <!--Grid column-->
      <div class="col-lg-2 col-md-12 mb-4">

        <!--Image-->
        <div class="view overlay z-depth-1-half">
          <img src="{% static 'img/cr7.jpg'%}" class="img-fluid"
            alt="">
          <a href="">
            <div class="mask rgba-white-light"></div>
          </a>
        </div>

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-2 col-md-6 mb-4">

        <!--Image-->
        <div class="view overlay z-depth-1-half">
          <img src="{% static 'img/hand.jpg'%}" class="img-fluid"
            alt="">
          <a href="">
            <div class="mask rgba-white-light"></div>
          </a>
        </div>

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-2 col-md-6 mb-4">

        <!--Image-->
        <div class="view overlay z-depth-1-half">
          <img src ="{% static 'img/volley.jpg'%} "  class="img-fluid"
            alt="">
          <a href="">
            <div class="mask rgba-white-light"></div>
          </a>
        </div>

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-2 col-md-12 mb-4">

        <!--Image-->
        <div class="view overlay z-depth-1-half">
          <img src="{% static 'img/tns.jpg'%}" class="img-fluid"
            alt="">
          <a href="">
            <div class="mask rgba-white-light"></div>
          </a>
        </div>

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-2 col-md-6 mb-4">

        <!--Image-->
        <div class="view overlay z-depth-1-half">
          <img src="{% static 'img/bsk.jpg'%}" class="img-fluid"
            alt="">
          <a href="">
            <div class="mask rgba-white-light"></div>
          </a>
        </div>

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-2 col-md-6 mb-4">

        <!--Image-->
        <div class="view overlay z-depth-1-half">
          <img src="{% static 'img/index.jpg'%}" class="img-fluid"
            alt="">
          <a href="">
            <div class="mask rgba-white-light"></div>
          </a>
        </div>

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

  </div>
  <!-- Footer Elements -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© suivez vos match en lignr via youtube
    <a href="https://mdbootstrap.com/education/bootstrap/"> .com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->


<!-- Footer  video-->
<footer class="page-footer font-small mdb-color darken-3 pt-4">

  <!-- Footer Elements -->
  <div class="container">

    <!--Grid row-->
    <div class="row d-flex justify-content-center">

      <!--Grid column-->
      <div class="col-md-6">

        <!-- Video -->
      <div class="embed-responsive embed-responsive-16by9 mb-4">
          <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/aYLUPHzsc6o"
            allowfullscreen></iframe>
        </div>

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

  </div>
  <!-- Footer Elements -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2018 Copyright:
    <a href="https://mdbootstrap.com/education/bootstrap/"> Sportflash.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->



<!-- Footer -->
<footer class="page-footer font-small mdb-color pt-4">

  <!-- Footer Links -->
  <div class="container text-center text-md-left">

    <!-- Footer links -->
    <div class="row text-center text-md-left mt-3 pb-3">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
        <h6 class="text-uppercase mb-4 font-weight-bold">Company name</h6>
        <p>suivez actualite du sport en regardant les match en direct fais des parie avec
           sportflash.</p>
      </div>
      <!-- Grid column -->

      <hr class="w-100 clearfix d-md-none">

      <!-- Grid column -->
      <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
        <h6 class="text-uppercase mb-4 font-weight-bold">Products</h6>
        <p>
          <a href="#!">betclic.com</a>
        </p>
        <p>
          <a href="#!">1xbet.com</a>
        </p>
        <p>
          <a href="#!">parie en ligne</a>
        </p>
        <p>
          <a href="#!">flashresultat</a>
        </p>
      </div>
      <!-- Grid column -->

      <hr class="w-100 clearfix d-md-none">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
        <h6 class="text-uppercase mb-4 font-weight-bold">Useful links</h6>
        <p>
          <a href="#!">Your Account</a>
        </p>
        <p>
          <a href="#!">Become an Affiliate</a>
        </p>
        <p>
          <a href="#!">Shipping Rates</a>
        </p>
        <p>
          <a href="#!">Help</a>
        </p>
      </div>

      <!-- Grid column -->
      <hr class="w-100 clearfix d-md-none">

      <!-- Grid column -->
      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
        <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
        <p>
          <i class="fas fa-home mr-3"></i> ABIDJAN/KOUMASSI, LOT 801, QT</p>
        <p>
          <i class="fas fa-envelope mr-3"></i> christianadjobi@gmail.com</p>
        <p>
          <i class="fas fa-phone mr-3"></i> +(225) 87 08 58 34</p>
        <p>
          <i class="fas fa-print mr-3"></i> +(225) 53 91 91 12</p>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Footer links -->

    <hr>

    <!-- Grid row -->
    <div class="row d-flex align-items-center">

      <!-- Grid column -->
      <div class="col-md-7 col-lg-8">

        <!--Copyright-->
        <p class="text-center text-md-left">© 2018 Copyright:
          <a href="">
            <strong> sporflash.com</strong>
          </a>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-5 col-lg-4 ml-lg-0">

        <!-- Social buttons -->
        <div class="text-center text-md-right">
          <ul class="list-unstyled list-inline">
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1">
                <i class="fab fa-facebook-f"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1">
                <i class="fab fa-twitter"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1">
                <i class="fab fa-google-plus-g"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1">
                <i class="fab fa-linkedin-in"></i>
              </a>
            </li>
          </ul>
        </div>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

</footer>
<!-- Footer -->


  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/style.js' %}"></script>
</body>

</html>